import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";  // importing fonts from google
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


//this metadata is edited for telling what a specific route is about. This is used for imporved SEO of our website.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>Shwetank header</header>
        {children}
        <footer>Shwetank footer</footer>
      </body>
    </html>
  );
}
